<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>bcl</string>
    <string>BCL</string>
   </array>
  <key>name</key>
  <string>bcl</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.bcl</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.double-slash.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bclass\b)|(\bfunc\b)|(\bstruct\b)|(\bthis\b)|(\bimport\b)|(\bfor\b))</string>
          <key>name</key>
          <string>support.function.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(((public)|(private))(?:(?=(\\?))\2.)*?)</string>
          <key>name</key>
          <string>storage.modifier.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bbyte\b)|(\bshort\b)|(\bint\b)|(\blong\b)|(\bhalf\b)|(\bfloat\b)|(\bdouble\b)|(\bhuge\b)|(\bstring\b)|(\bchar\b))</string>
          <key>name</key>
          <string>storage.type.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\bprintln\b)|(\bprint\b))</string>
          <key>name</key>
          <string>keyword.other.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\b=\b)|(\b==\b)|(\b-&gt;\b)|(\b&gt;\b)|&gt;|(\b&gt;=\b)|(\b&lt;=\b))</string>
          <key>name</key>
          <string>keyword.operator.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(([\x{0022}\x{0027}])(?:(?=(\\?))\2.)*?\1)</string>
          <key>name</key>
          <string>keyword.operator.bcl</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-z][a-z0-9]*)</string>
          <key>name</key>
          <string>keyword.bcl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.bcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.bcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>((\:\:)|;|)</string>
          <key>name</key>
          <string>punctuation.definition.comment.bcl</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.bcl</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.bcl</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.double-slash.bcl</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.bcl</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.definition.comment.bcl</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.double-slash.bcl</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.line.double-slash.bcl</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.double-slash.bcl</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.bcl</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>