name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        echo 'Running setup / Installing dependencies'
        sudo apt install llvm-11
        sudo apt install python3.11

    - name: Run tests
      run: |
        echo 'running tests'
        make unittest
