# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
    - name: Install dependencies
      run: |
        sudo ldconfig
        sudo apt-get install libc6-dev
        sudo apt install gcc-multilib
        sudo apt install lld-15
        # setup virtual environment
        python -m pip install --upgrade pip
        python3.12 -m venv env
        # install simple dependencies
        env/bin/pip install flake8 pytest rply
        # install llvmlite and it's dependencies
        conda install -c conda-forge libstdcxx-ng=12
        conda install -y -q -c numba llvmdev="15.*" libxml2
        conda install cmake
        env/bin/pip install -r requirements.txt
    - name: Run Tests
      run: |
        env/bin/python setup.py test
