# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
    - name: Install dependencies
      run: |
        # setup virtual environment
        python -m pip install --upgrade pip
        python3.11 -m venv env
        # install simple dependencies
        env/bin/pip install flake8 pytest rply
        # install llvmlite and it's dependencies
        conda install -c conda-forge libstdcxx-ng=12
        conda install -y -q -c numba/label/dev llvmdev="14.*" libxml2
        conda install cmake
        env/bin/pip install git+https://github.com/Hassium-Software/llvmlite-lld.git
    - name: Run Tests
      run: |
        env/bin/python setup.py test
